apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: demo-vm
spec:
  running: true
  template:
    spec:
      domain:
        resources:
          requests:
            memory: 128Mi
            cpu: 1
        devices:
          disks:
          - name: rootdisk
            disk:
              bus: virtio
      volumes:
      - name: rootdisk
        hostDisk:
          path: /tmp/cirros.qcow2
          type: Disk
